### ISSUE TITLE
09 - week - Suncoast Overflow

### ISSUE THREAD

**Issue by Carla-Joseph** [Carla-Joseph/assignments#32]
A good way to practice the concepts of creating full-stack web applications is to duplicate an existing site. For this project, you will be creating a copy of a site that you know very well, StackOverflow.

## Objectives

- Create a full-stack web app, from the database to the API, to the styled and responsive frontend.

## Requirements

Create an anonymous question and answer site that allows users to up-vote and down-vote questions and answers.

Here are the user stories for this application:

- [ ] As a user I should be able to view and search previously asked questions.
- [ ] As a user I should be able to view a specific question and all of its answers.
- [ ] As a user I should be able to anonymously post a question.
- [ ] As a user I should be able to answer an existing question.
- [ ] As a user I should be able to upvote or downvote a question.
- [ ] As a user I should be able to upvote or downvote an answer.

### Explorer Mode

You have a choice to create a custom design or to start with existing HTML and CSS we provide.

- [ ] If you are going to create a custom design:
  - [ ] Create wireframes for your app.
- [ ] Create an ERD for the core functionality.
- [ ] Generate your `dotnet new` project.
- [ ] If you are going to create a custom design:
- [ ] Create the _static_ HTML and CSS for all the pages the app will need.
- [ ] If you are going to use our starter files:
- [ ] Update the design or layout to fit your needs. Practice some HTML and CSS.
- [ ] Create React components for each page
- [ ] Setup React Router to render these, but still just static representations

### Day 2

- [ ] Generate your database migrations based on your ERD.
- [ ] Insert sample questions, and corresponding answers into your database.
- [ ] Create the API for generating the list of questions to show on the home page.
- [ ] Create the API for posting a new question.

### Day 3

- [ ] Create the API for fetching a single question along with its answers.
- [ ] Create the API for posting a new question.

**Comment by Carla-Joseph** [comment]
https://github.com/Carla-Joseph/SuncoastOverflow

**Comment by gstark** [comment]
Thanks for completing this!

**Comment by Carla-Joseph** [comment]
Your homework **09 - week - Suncoast Overflow** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74dc376b990fefa4b57db26c0337e9d122b96fd7/giphy-16.gif)
> &ldquo;Well done!&rdquo;
