### ISSUE TITLE
02 - 02 C# Iteration - Working with LINQ

### ISSUE THREAD

**Issue by Carla-Joseph** [Carla-Joseph/assignments#5]
Learning programming takes practice and the best practice is repetition. This
exercise will allow you time to work on the basics of .NET and how to apply that
logic to solving problems.

## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/net-iteration) to
   your own account.
2. Change into your projects directory:
3. Clone your repository:
   `git clone https://github.com/YOUR_NAME_HERE/net-iteration`
4. Change into your project's directory: `cd net-iteration`
5. Install the dependencies: `dotnet restore`
6. Open in your editor: `code .`
7. Start the test runner: `dotnet watch test`
8. Open `Iterations.cs` and work on functions until the test passes. Once you
   are done with a test you can move to the next one by removing the
   `(Skip = "Remove to run test")` from the `Fact` attribute. There are a total
   of 10 questions.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation to find what kind of helpful functions
might already be in C#.

- [String Functions](https://www.c-sharpcorner.com/blogs/some-string-functions-of-c-sharp).
- [Official LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/)

**Comment by Carla-Joseph** [comment]
https://github.com/Carla-Joseph/net-iteration

I'm almost done but I attempted #9 and 10 at the same time and dotnet watch test didn't specify which one is incorrect. If you would be so kind to inform me, that would be great!

**Comment by gstark** [comment]
I don't think you pushed the latest version of the code. Would you please push that code so I may review.

**Comment by Carla-Joseph** [comment]
https://github.com/Carla-Joseph/net-iteration/blob/master/Iterations.cs

**Comment by gstark** [comment]
So for #9 this would return the index of a string that is _exactly_ equal to `needle` but you need to find the index of a an element that `contains` needle, so you need something more complex than just `IndexOf`

#10 looks good to me.

**Comment by gstark** [comment]
I'm going to accept this homework as complete. Feel free to go back and work on #9.

**Comment by Carla-Joseph** [comment]
Your homework **02 - 02 C# Iteration - Working with LINQ** was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--337d5db9d88e083c06c448999f852548342972b5/giphy-18.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/83)**__
